[package]
name = "alicesaidhi/jabby"
description = "Jecs debugger built with Vide"
version = "0.2.0-rc.4"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["out", ".vscode", "aftman.toml", ".luaurc", "test.project.json", "todo.md"]
realm = "shared"

[dependencies]
pebble = "alicesaidhi/pebble@0.1.0-rc.8"
vide = "centau/vide@0.3.1"
ecr = "centau/ecr@0.8.0"
t = "corecii/greentea@0.4.7"